import os
import json

# Define paths relative to the project root directory
PATHS_DIR = os.path.join("src", "main", "deploy", "pathplanner", "paths")
OUTPUT_FILE = os.path.join("src", "main", "java", "frc", "robot", "AutonConstants.java")

def format_variable_name(filename, suffix):
    # Converts "Score-Piece_3.path" -> "SCORE_PIECE_3_START"
    base = os.path.splitext(filename)[0]
    clean = base.replace("-", "_").replace(" ", "_").upper()
    return f"{clean}_{suffix}"

def generate_java_file():
    if not os.path.exists(PATHS_DIR):
        print(f"Error: PathPlanner directory not found at: {PATHS_DIR}")
        return

    java_lines = [
        "package frc.robot;",
        "",
        "import edu.wpi.first.math.geometry.Pose2d;",
        "import edu.wpi.first.math.geometry.Rotation2d;",
        "",
        "/**",
        " * Automatically generated by generate_auton_constants.py.",
        " * Do not manually edit this file; re-run the generator script instead.",
        " */",
        "public final class AutonConstants {",
        "    // Static utility class, prevent instantiation",
        "    private AutonConstants() {}",
        ""
    ]

    found_files = False

    # Scan directory for all .path files
    for filename in sorted(os.listdir(PATHS_DIR)):
        if not filename.endswith(".path"):
            continue
            
        found_files = True
        file_path = os.path.join(PATHS_DIR, filename)
        
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                data = json.load(f)
        except Exception as e:
            print(f"Skipping {filename} due to JSON read error: {e}")
            continue

        # Compatibility layer handling PathPlanner file format variants
        waypoints = data.get('waypoints')
        if waypoints is None and 'path' in data:
            waypoints = data['path'].get('waypoints', [])

        if not waypoints or len(waypoints) < 2:
            print(f"Skipping {filename}: Not enough waypoints found.")
            continue

        # Extract values for Start and End points
        start_pt = waypoints[0]
        end_pt = waypoints[-1]

        start_x, start_y = start_pt['anchor']['x'], start_pt['anchor']['y']
        start_rot = start_pt.get('holonomicRotation', 0.0)

        end_x, end_y = end_pt['anchor']['x'], end_pt['anchor']['y']
        end_rot = end_pt.get('holonomicRotation', 0.0)

        # Build clean variable names
        start_var = format_variable_name(filename, "START")
        end_var = format_variable_name(filename, "END")

        # Format lines using WPILib formatting
        java_lines.append(f"    // Poses from {filename}")
        java_lines.append(f"    public static final Pose2d {start_var} = new Pose2d({start_x:.3f}, {start_y:.3f}, Rotation2d.fromDegrees({start_rot:.1f}));")
        java_lines.append(f"    public static final Pose2d {end_var} = new Pose2d({end_x:.3f}, {end_y:.3f}, Rotation2d.fromDegrees({end_rot:.1f}));")
        java_lines.append("")

    java_lines.append("}")

    if not found_files:
        print("No .path files were found to process.")
        return

    # Ensure output directory exists before writing
    os.makedirs(os.path.dirname(OUTPUT_FILE), exist_ok=True)
    
    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write("\n".join(java_lines))
        
    print(f"Success! Generated constants for your paths inside: {OUTPUT_FILE}")

if __name__ == '__main__':
    generate_java_file()
